export enum RestaurantMSG {
  CREATE = 'CREATE_RESTAURANT',
  FIND_ALL = 'FIND_RESTAURANTS',
  FIND_ONE = 'FIND_RESTAURANT',
  UPDATE = 'UPDATE_RESTAURANT',
  DELETE = 'DELETE_RESTAURANT',
  ADD_ORDER = 'ADD_ORDER',
  TASK = 'TASK',
}
